language: php

php:
  - 5.3
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make build-dantechdk.make ../dantechdk.com
  - cd ../dantechdk.com
  - sudo chmod -R 777 sites/
  
  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
  # Install site
  - drush si minimal --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="dantechdk.com" --yes
  - drush en dantech_deploy -y
  - drush cc all --yes

script:
  - test -d profiles/dantechdk
  - test -d sites/all/modules/contrib
